name: pytorch-env

channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults

dependencies:
  - boto3
  - cuda-libraries-dev=11.7
  - cuda-profiler-api
  - cudatoolkit=11.7
  - cxxfilt
  - packaging
  - pip
  - pip:
    - -r requirements.txt
  - pytest
  - python=3
  - pytorch=1.13.0
  - pyyaml
  - setuptools
  - six
  - torchvision=0.14.0
  - tqdm
