name: pytorch-env

channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults

dependencies:
  - boto3
  - cudatoolkit=11.3
  - cudatoolkit-dev=11.3
  - cxxfilt
  - packaging
  - pip
  - pip:
    - -r requirements.txt
  - pytest
  - python=3
  - pytorch=1.12.1
  - pyyaml
  - setuptools
  - six
  - torchvision=0.13.1
  - tqdm
